apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: main #Service looks here
    spec:
      containers:
        - env:
            - name: CLUSTER_IP_POSTGRES
              value: "{{ .Values.db.clusterIPPostgres }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.db.ports.POSTGRES_PORT }}"
            - name: REDIS_PORT
              value: "{{ .Values.db.ports.REDIS_PORT }}"
            - name: KAFKA_HOST
              value: "kafka-cp-kafka:9092"
            - name: CLUSTER_IP_REDIS
              value: "{{ .Values.db.clusterIPRedis }}"
            - name: SERVER_PORT
              value: "{{ .Values.portMain }}"
          name: main-deployment
          image: main1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.portMain }} #Port on Pod
