apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app : store
spec:
  selector:
    matchLabels:
      app: store
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: store
    spec:
        containers:
            - env:
                - name: CLUSTER_IP_POSTGRES
                  value: "{{ .Values.db.clusterIPPostgres }}"
                - name: POSTGRES_PORT
                  value: "{{ .Values.db.ports.POSTGRES_PORT }}"
                - name: KAFKA_HOST
                  value: "kafka-cp-kafka:9092"
                - name: SERVER_PORT
                  value: "{{ .Values.portStore }}"
              name: store-deployment
              image: store1:latest
              imagePullPolicy: Never
              ports:
                - containerPort: {{ .Values.portStore }} #Port on Pod
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: store-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name:  store-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

