apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: {{ .Values.db.clusterIPPostgres }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.db.ports.POSTGRES_PORT }}
      nodePort: 31432
  selector:
    app: postgres